Tz naive timestamps conversion to local
Arize-ai/phoenix pull request #1066
Opened 2023-08-09 08:08 UTC by pbadhe

Resolves #1060 
Tackles strings & datetime types.

2023-08-09 15:01 UTC, mikeldking requested changes
@pbadhe thanks so much for your contribution! I think we need to preserve the UTC storage. The best approach here might be starting with a notebook and plotting out non-timezone aware timestamps into histograms and comparing how it looks in phoenix. I think you might find what I outlined to be true. Shoot me a message if this is still confusing. I can sketch out the issue a bit more.

2023-08-09 15:16 UTC, pbadhe commented on src/phoenix/datasets/dataset.py
> +            datetime.now().astimezone().tzinfo
Yep gotcha, had the same doubts while implementing. Will first localize if timestamps are timezone naive, then convert to UTC.

2023-08-10 21:20 UTC, mikeldking commented
Thanks @pbadhe - I tested it a bit and found some interesting facts:

`datetime.now().astimezone().tzinfo)` in colab is always UTC 🤯 So this doesn't really work - but it does for local notebooks so that's good.

I need to pin the time to the end of day for certain granularities otherwise the day boundaries get all mixed up. I'll do this in a follow-up.

Thanks again!

2023-08-10 21:20 UTC, mikeldking approved these changes

2023-08-10 21:33 UTC, merged