Online Periodic Eval Scripts
Arize-ai/phoenix pull request #2598
Opened 2024-03-15 16:24 UTC by jlopatec

Scripts that allow you to run periodic Evals as a chron job

2024-03-15 19:01 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    return session
```suggestion
    return px.launch_app()
```
Not sure this is even needed. It's one line

2024-03-15 19:03 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    trace_df = px.Client(endpoint=str(session.url)).get_trace_dataset()
you only need client. Also the session URL is technically not necessarily the endpoint. Notably in sagemaker notebooks. Why is this param needed

2024-03-15 19:03 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    spans_df = px.Client(endpoint=str(session.url)).get_spans_dataframe("span_kind == 'RETRIEVER'")
badly named. These are only retriever spans

2024-03-15 19:13 UTC, mikeldking requested changes
These files are pretty darn confusing. I would be un-comfortable maintaining these as is. Let's re-group on this.

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +        openai_api_key=os.environ["OPENAI_API_KEY"]
this should not be necessary

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    model_name = 'text-embedding-ada-002'
this is confusing - why not just inline it on 71?

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    handler = StdOutCallbackHandler()
Is this needed?

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    chat_model_name = "gpt-4-turbo-preview"
Variables not re-used. It can be condensed

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    retrieved_documents_df = get_retrieved_documents(px.Client())
initialize the client once

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +        session = px.active_session()
this is super messy do this outside of the try catch

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +    tds._id = "b4165a34-2020-4e9b-98ec-26c5d7e954d4"
avoid string copy pasta

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +        "http://storage.googleapis.com/arize-phoenix-assets/datasets/unstructured/llm/context-retrieval/langchain-pinecone/langchain_pinecone_query_dataframe_with_user_feedbackv2.parquet"
we are pulling for a dataframe about pinecone and shoving it

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_generate_test_data.py
> +def run_tests(generate_queries=False):
why does this exist here if it's in the other file?

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_periodic_eval_chron.py
> +    #spans_df = session.get_spans_dataframe("span_kind == 'RETRIEVER'")
can we delete these

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_periodic_eval_chron.py
> +        os.environ["OPENAI_API_KEY"] = openai_api_key
This doesn't make a ton of sense - these are scripts. Shouldn't this just be a pre-requisite and you throw?

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_periodic_eval_chron.py
> +    TRACE_DATA_UUID = "b4165a34-2020-4e9b-98ec-26c5d7e954d4"
This can be scoped as a constant outside of main

2024-03-15 19:13 UTC, mikeldking commented on scripts/data/online_evals_periodic_eval_chron.py
> +            tds = TraceDataset.load(HARD_CODE_UUID)
This value is missing HARD_CODE_UUID

2024-03-20 01:45 UTC, axiomofjoy commented
Closing this PR. An equivalent example has been created in #2614

2024-03-20 01:45 UTC, closed without merging