new hosted_phoenix tutorials
Arize-ai/phoenix pull request #4018
Opened 2024-07-25 22:09 UTC by exiao

I wanted to add two new .ipynb stored on repo instead of being stored in my personal GitHub account.

2024-07-29 16:41 UTC, mikeldking commented
@exiao thanks for the PR. Could you address the CI failures? The procedure for fixing the notebook formats should be in the DEVELOPMENT guide. Let us know if you get stuck

2024-07-30 10:11 UTC, exiao commented
I have read the CLA Document and I hereby sign the CLA.

2024-07-30 10:14 UTC, exiao commented
I have read the CLA Document and I hereby sign the CLA

2024-07-30 10:16 UTC, exiao commented
I have read the CLA Document and I hereby sign the CLA

2024-07-30 15:45 UTC, mikeldking commented
recheck

2024-07-30 16:20 UTC, Jgilhuly approved these changes
Looks great!

2024-07-30 16:44 UTC, mikeldking commented on tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #6.    phoenix_df = px_client.get_spans_dataframe()
</pre><p>the name here is a bit confusing. Why not spans_df?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Arize-ai/phoenix/pull/4018/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2024-07-30 17:58 UTC, mikeldking requested changes
The examples should use project name but I don't see the corresponding code. Also do you think it's worth having a more comprehensive tutorial that includes evals? Otherwise these tutorials could be consolidated as they just show you how to setup endpoints and headers. There's no real need for both

2024-07-30 19:21 UTC, mikeldking commented on tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #19.    px_client.get_spans_dataframe(project_name="rechat", root_spans_only=True)
</pre><p>I don't see project name in any of the code above. You sure this works? also why the root_spans_only flag here?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Arize-ai/phoenix/pull/4018/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2024-07-30 19:21 UTC, mikeldking commented on tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #16.        dataset_name="test-dataset-2",
</pre><p>Can you make this dataset more realistic?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Arize-ai/phoenix/pull/4018/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2024-08-23 03:36 UTC, mikeldking commented
These need work - but they are better than not having them. Will work with @Jgilhuly to freshen these up

2024-08-23 03:36 UTC, merged