feat(prompts!): prompt template management
Arize-ai/phoenix pull request #5724
Opened 2024-12-12 22:10 UTC by mikeldking

resolves #5582

2024-12-12 22:46 UTC, RogerHYang requested changes
blocking feature branch

2025-02-19 23:10 UTC, axiomofjoy approved these changes

2025-02-19 23:10 UTC, RogerHYang approved these changes

2025-02-19 23:17 UTC, mikeldking commented
![image](https://github.com/user-attachments/assets/17bb4e7b-d456-499c-ae64-ce07cfd30930)

2025-02-19 23:19 UTC, merged